# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
channel = "stable-2024-06-25"
components = [ "rustfmt", "rustc-dev" ]
targets = [ "wasm32-unknown-unknown" ]
profile = "default"
